version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: fitocube-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - fitocube_net
  db:
    image: postgres:15
    container_name: db-embedded
    environment:
      - POSTGRES_DB=embedded
      - POSTGRES_USER=embedded
      - POSTGRES_PASSWORD=embedded
    ports:
      - 5555:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U study -d study" ]
      interval: 5s
      timeout: 1s
      retries: 10
    restart: unless-stopped

networks:
  fitocube_net:
    driver: bridge

volumes:
  db-data:
